version: '3'

services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./data/files/static:/data/files/static
      - ./data/files/logs:/data/files/logs
    restart: always
    env_file: ./.env
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    expose:
      - 9000
    volumes:
      - ./data/files/static:/data/files/static
    restart: always
    env_file: ./.env

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_USER: admin
      MYSQL_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: mt
    ports:
      - 13306:3306
    volumes:
      - ./docker/db/conf:/etc/mysql/conf.d
      - ./data/db:/var/lib/mysql
    env_file: ./.env

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '8081:1080'
